version: '3.8'

networks:
  net:
    name: vh-net
    driver: bridge
    ipam:
      driver: default
      config: 
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    networks:
      - net
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - net
    volumes:
      - ./frontend:/app
volumes:
  db-data: